services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: tienda_panaderia
      POSTGRES_USER: tienda
      POSTGRES_PASSWORD: tienda123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_ENGINE: postgres
      PG_HOST: db
      PG_PORT: 5432
      PG_DB: tienda_panaderia
      PG_USER: tienda
      PG_PASS: tienda123
      FRONTEND_ORIGIN: http://localhost:4200,http://localhost:8080
      PORT: 5000
      SEED_DUENO_USER: dueno
      SEED_DUENO_PASS: dueno123
      SEED_VENDEDOR_USER: vendedora
      SEED_VENDEDOR_PASS: venta123
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  pgdata:
